community: remove integration as the product has changed (#159)
This code dates back to when [Tigris Data][1] was a database as a
service. That product has since been sunset and the current product is
globally distributed object storage.

Removing this code as there is no possible way for it to work.

[1]: https://www.tigrisdata.com

Ref: TIG-4616

Twitter handle: @TigrisData

I am running into a problem with the removal though, when I run tests
locally I get an error that the tigris import doesn't exist:

```
FAILED tests/unit_tests/vectorstores/test_indexing_docs.py::test_compatible_vectorstore_documentation - ModuleNotFoundError: No module named 'langchain_community.vectorstores.tigris'
FAILED tests/unit_tests/imports/test_langchain_proxy_imports.py::test_vectorstores - AttributeError: module langchain_community.vectorstores has no attribute Tigris
FAILED tests/unit_tests/vectorstores/test_imports.py::test_all_imports_exclusive - ModuleNotFoundError: No module named 'langchain_community.vectorstores.tigris'
FAILED tests/unit_tests/vectorstores/test_imports.py::test_all_imports - AssertionError: assert {'PGVector', 'SemaDB', 'TiDBVectorStore', 'LanceDB', 'MyScale', 'MomentoVectorIndex', 'USearch', 'ZepVectorStore', 'LLMRails', 'OracleVS', 'Dingo', 'Redis', 'BaiduVectorDB', 'PathwayVectorClient', 'BigQueryVectorSearch', 'KDBAI', 'Marqo', 'Pinecone', 'Relyt', 'Chroma', 'TimescaleVector', 'ManticoreSearchSettings', 'DashVector', 'NeuralDBVectorStor...
FAILED tests/unit_tests/test_imports.py::test_importable_all - ModuleNotFoundError: No module named 'langchain_community.vectorstores.tigris'
FAILED tests/unit_tests/test_imports.py::test_init_files_properly_defined - AssertionError: Missing imports: {'Tigris'} in file path: /Users/xe/Code/Xe/langchain-community/libs/community/langchain_community/vectorstores/__init__.py
```

Where is this coming from so I can fix it?

---------

Signed-off-by: Xe Iaso <xe@tigrisdata.com>
Co-authored-by: Mason Daugherty <mason@langchain.dev>
Co-authored-by: Mason Daugherty <github@mdrxy.com>